INSERT INTO cliente(num_cliente, ubicacion) VALUES (1, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (2, 'Magdalena Contreras');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (3, 'Milpa Alta');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (4, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (5, 'Benito Juárez');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (6, 'Coyoacán');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (7, 'Coyoacán');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (8, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (9, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (10, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (11, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (12, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (13, 'Cuajimalpa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (14, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (15, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (16, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (17, 'Iztacalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (18, 'Cuauhtémoc');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (19, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (20, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (21, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (22, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (23, 'Tláhuac');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (24, 'Gustavo A. Madero');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (25, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (26, 'Cuauhtémoc');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (27, 'Cuajimalpa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (28, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (29, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (30, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (31, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (32, 'Coyoacán');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (33, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (34, 'Coyoacán');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (35, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (36, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (37, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (38, 'Azcapotzalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (39, 'Cuauhtémoc');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (40, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (41, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (42, 'Cuajimalpa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (43, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (44, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (45, 'Coyoacán');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (46, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (47, 'Cuauhtémoc');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (48, 'Iztapalapa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (49, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (50, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (51, 'Azcapotzalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (52, 'Tláhuac');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (53, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (54, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (55, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (56, 'Iztapalapa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (57, 'Iztacalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (58, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (59, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (60, 'Coyoacán');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (61, 'Iztacalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (62, 'Cuajimalpa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (63, 'Iztacalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (64, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (65, 'Tláhuac');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (66, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (67, 'Coyoacán');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (68, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (69, 'Gustavo A. Madero');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (70, 'Gustavo A. Madero');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (71, 'Benito Juárez');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (72, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (73, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (74, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (75, 'Iztapalapa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (76, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (77, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (78, 'Benito Juárez');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (79, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (80, 'Iztapalapa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (81, 'Miguel Hidalgo');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (82, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (83, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (84, 'Iztapalapa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (85, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (86, 'Coyoacán');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (87, 'Magdalena Contreras');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (88, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (89, 'Coyoacán');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (90, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (91, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (92, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (93, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (94, 'Gustavo A. Madero');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (95, 'Cuajimalpa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (96, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (97, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (98, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (99, 'Miguel Hidalgo');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (100, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (101, 'Iztacalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (102, 'Miguel Hidalgo');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (103, 'Tláhuac');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (104, 'Iztacalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (105, 'Milpa Alta');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (106, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (107, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (108, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (109, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (110, 'Iztacalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (111, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (112, 'Iztapalapa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (113, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (114, 'Azcapotzalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (115, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (116, 'Azcapotzalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (117, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (118, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (119, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (120, 'Coyoacán');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (121, 'Tláhuac');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (122, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (123, 'Azcapotzalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (124, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (125, 'Benito Juárez');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (126, 'Tláhuac');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (127, 'Coyoacán');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (128, 'Iztacalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (129, 'Magdalena Contreras');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (130, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (131, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (132, 'Cuajimalpa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (133, 'Cuajimalpa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (134, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (135, 'Cuauhtémoc');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (136, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (137, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (138, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (139, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (140, 'Coyoacán');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (141, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (142, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (143, 'Iztacalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (144, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (145, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (146, 'Iztapalapa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (147, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (148, 'Cuauhtémoc');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (149, 'Milpa Alta');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (150, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (151, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (152, 'Gustavo A. Madero');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (153, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (154, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (155, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (156, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (157, 'Cuajimalpa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (158, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (159, 'Azcapotzalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (160, 'Cuauhtémoc');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (161, 'Azcapotzalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (162, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (163, 'Iztapalapa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (164, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (165, 'Miguel Hidalgo');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (166, 'Coyoacán');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (167, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (168, 'Tláhuac');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (169, 'Iztacalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (170, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (171, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (172, 'Iztacalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (173, 'Gustavo A. Madero');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (174, 'Iztacalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (175, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (176, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (177, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (178, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (179, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (180, 'Coyoacán');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (181, 'Cuauhtémoc');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (182, 'Gustavo A. Madero');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (183, 'Cuauhtémoc');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (184, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (185, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (186, 'Milpa Alta');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (187, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (188, 'Tláhuac');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (189, 'Cuauhtémoc');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (190, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (191, 'Coyoacán');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (192, 'Gustavo A. Madero');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (193, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (194, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (195, 'Tláhuac');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (196, 'Azcapotzalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (197, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (198, 'Cuauhtémoc');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (199, 'Magdalena Contreras');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (200, 'Cuajimalpa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (201, 'Coyoacán');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (202, 'Azcapotzalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (203, 'Coyoacán');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (204, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (205, 'Milpa Alta');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (206, 'Cuajimalpa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (207, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (208, 'Milpa Alta');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (209, 'Azcapotzalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (210, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (211, 'Iztacalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (212, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (213, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (214, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (215, 'Cuauhtémoc');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (216, 'Cuauhtémoc');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (217, 'Cuauhtémoc');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (218, 'Azcapotzalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (219, 'Tláhuac');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (220, 'Milpa Alta');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (221, 'Azcapotzalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (222, 'Tláhuac');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (223, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (224, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (225, 'Iztacalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (226, 'Coyoacán');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (227, 'Milpa Alta');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (228, 'Azcapotzalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (229, 'Miguel Hidalgo');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (230, 'Iztapalapa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (231, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (232, 'Milpa Alta');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (233, 'Iztacalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (234, 'Gustavo A. Madero');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (235, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (236, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (237, 'Iztapalapa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (238, 'Iztapalapa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (239, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (240, 'Cuajimalpa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (241, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (242, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (243, 'Magdalena Contreras');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (244, 'Iztacalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (245, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (246, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (247, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (248, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (249, 'Cuauhtémoc');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (250, 'Azcapotzalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (251, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (252, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (253, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (254, 'Benito Juárez');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (255, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (256, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (257, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (258, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (259, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (260, 'Tláhuac');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (261, 'Coyoacán');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (262, 'Benito Juárez');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (263, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (264, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (265, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (266, 'Cuajimalpa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (267, 'Tláhuac');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (268, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (269, 'Cuauhtémoc');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (270, 'Coyoacán');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (271, 'Iztapalapa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (272, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (273, 'Gustavo A. Madero');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (274, 'Tláhuac');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (275, 'Iztapalapa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (276, 'Iztacalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (277, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (278, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (279, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (280, 'Miguel Hidalgo');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (281, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (282, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (283, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (284, 'Cuajimalpa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (285, 'Cuauhtémoc');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (286, 'Gustavo A. Madero');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (287, 'Benito Juárez');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (288, 'Cuauhtémoc');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (289, 'Magdalena Contreras');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (290, 'Milpa Alta');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (291, 'Iztapalapa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (292, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (293, 'Cuajimalpa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (294, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (295, 'Iztapalapa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (296, 'Coyoacán');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (297, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (298, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (299, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (300, 'Magdalena Contreras');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (301, 'Benito Juárez');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (302, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (303, 'Iztacalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (304, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (305, 'Gustavo A. Madero');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (306, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (307, 'Milpa Alta');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (308, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (309, 'Iztacalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (310, 'Tláhuac');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (311, 'Magdalena Contreras');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (312, 'Miguel Hidalgo');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (313, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (314, 'Milpa Alta');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (315, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (316, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (317, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (318, 'Tláhuac');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (319, 'Gustavo A. Madero');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (320, 'Gustavo A. Madero');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (321, 'Benito Juárez');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (322, 'Iztacalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (323, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (324, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (325, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (326, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (327, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (328, 'Tláhuac');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (329, 'Benito Juárez');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (330, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (331, 'Cuajimalpa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (332, 'Miguel Hidalgo');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (333, 'Magdalena Contreras');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (334, 'Coyoacán');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (335, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (336, 'Milpa Alta');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (337, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (338, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (339, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (340, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (341, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (342, 'Cuauhtémoc');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (343, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (344, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (345, 'Tláhuac');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (346, 'Tláhuac');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (347, 'Milpa Alta');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (348, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (349, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (350, 'Milpa Alta');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (351, 'Miguel Hidalgo');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (352, 'Cuajimalpa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (353, 'Azcapotzalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (354, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (355, 'Benito Juárez');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (356, 'Iztapalapa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (357, 'Iztapalapa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (358, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (359, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (360, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (361, 'Milpa Alta');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (362, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (363, 'Miguel Hidalgo');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (364, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (365, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (366, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (367, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (368, 'Iztacalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (369, 'Iztapalapa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (370, 'Gustavo A. Madero');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (371, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (372, 'Cuajimalpa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (373, 'Gustavo A. Madero');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (374, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (375, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (376, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (377, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (378, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (379, 'Magdalena Contreras');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (380, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (381, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (382, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (383, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (384, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (385, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (386, 'Azcapotzalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (387, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (388, 'Tláhuac');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (389, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (390, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (391, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (392, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (393, 'Milpa Alta');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (394, 'Coyoacán');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (395, 'Gustavo A. Madero');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (396, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (397, 'Azcapotzalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (398, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (399, 'Iztapalapa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (400, 'Azcapotzalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (401, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (402, 'Tláhuac');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (403, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (404, 'Coyoacán');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (405, 'Iztapalapa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (406, 'Azcapotzalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (407, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (408, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (409, 'Miguel Hidalgo');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (410, 'Milpa Alta');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (411, 'Cuauhtémoc');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (412, 'Cuajimalpa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (413, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (414, 'Tláhuac');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (415, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (416, 'Tláhuac');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (417, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (418, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (419, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (420, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (421, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (422, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (423, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (424, 'Iztacalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (425, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (426, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (427, 'Azcapotzalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (428, 'Miguel Hidalgo');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (429, 'Iztacalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (430, 'Tláhuac');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (431, 'Cuajimalpa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (432, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (433, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (434, 'Tláhuac');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (435, 'Miguel Hidalgo');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (436, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (437, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (438, 'Azcapotzalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (439, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (440, 'Iztacalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (441, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (442, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (443, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (444, 'Iztapalapa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (445, 'Milpa Alta');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (446, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (447, 'Miguel Hidalgo');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (448, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (449, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (450, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (451, 'Milpa Alta');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (452, 'Tláhuac');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (453, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (454, 'Azcapotzalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (455, 'Cuauhtémoc');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (456, 'Benito Juárez');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (457, 'Cuajimalpa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (458, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (459, 'Tláhuac');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (460, 'Milpa Alta');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (461, 'Gustavo A. Madero');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (462, 'Milpa Alta');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (463, 'Azcapotzalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (464, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (465, 'Milpa Alta');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (466, 'Tláhuac');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (467, 'Coyoacán');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (468, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (469, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (470, 'Miguel Hidalgo');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (471, 'Iztapalapa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (472, 'Azcapotzalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (473, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (474, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (475, 'Benito Juárez');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (476, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (477, 'Gustavo A. Madero');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (478, 'Gustavo A. Madero');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (479, 'Azcapotzalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (480, 'Gustavo A. Madero');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (481, 'Álvaro Obregón');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (482, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (483, 'Magdalena Contreras');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (484, 'Cuauhtémoc');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (485, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (486, 'Cuajimalpa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (487, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (488, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (489, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (490, 'Cuajimalpa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (491, 'Cuajimalpa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (492, 'Tláhuac');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (493, 'Xochimilco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (494, 'Milpa Alta');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (495, 'Iztacalco');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (496, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (497, 'Cuajimalpa');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (498, 'Venustiano Carranza');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (499, 'Tlalpan');
INSERT INTO cliente(num_cliente, ubicacion) VALUES (500, 'Tlalpan');
